### ISSUE TITLE
task from milestone: remove logging (change to logging-module)

### ISSUE THREAD

**Issue by JonasNapierski** [zirkumflexlab/leni-py#15]
The title is a little bit missleading. In this case there is an implementation of a logging system in the code, but it is just bad. We will switch from a self created logging system to the offical `logging` module. 

## Todo's
- [x] Logging Todos Complete
- [x] create a concept, what is a good logging message, inspect on different logging levels 
- [x] remove old log statements.
- [x] re-implement the new logging statements.
- [x] create a log config example
- [x] create a class where in future use the logging can directly be manupilated by differend command flags.

## Tests
- [ ] #25
- [ ] Test if logging works
- [ ] Test logging_config module/class
- [ ] Test creating of log files

## Documentation
- [ ] Logging Documentation Complete
- [ ] what does which log message mean?
- [ ] how to configure the logger
- [ ] where can i find my log files?

**Comment by JonasNapierski** [comment]
> create a class where in future use the logging can directly be manupilated by differend command flags.
This is already done by the default logging module in python, which we use. For more information [python doc logging](https://docs.python.org/3/howto/logging.html#logging-to-a-file)
